version: "3.7"
services:
  seasonalbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seasonalbot
    init: true

    restart: always

    environment:
      - SEASONALBOT_TOKEN=yourtokenhere
      - SEASONALBOT_DEBUG=true
    # - SEASONALBOT_GUILD=
    # - SEASONALBOT_ADMIN_ROLE_ID=
    # - CHANNEL_ANNOUNCEMENTS=
    # - CHANNEL_DEVLOG=
    # - SEASON_OVERRIDE=

    volumes:
      - /opt/pythondiscord/seasonalbot/log:/bot/bot/log
      - /opt/pythondiscord/seasonalbot/data:/bot/data
